services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: domaindocs_postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: ['postgres', '-c', 'wal_level=logical']
    healthcheck:
      test: ['CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

#  rabbitmq:
#    image: rabbitmq:3.11-management-alpine
#    container_name: domaindocs_rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#      RABBITMQ_DEFAULT_VHOST: /
#
#  debezium:
#    image: debezium/server:2.4
#    container_name: domaindocs_debezium-server
#    ports:
#      - 8080:8080
#    volumes:
#      - ./debezium:/debezium/conf
#    depends_on:
#      - rabbitmq
#      - postgres

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: domaindocs_supertokens
    depends_on:
      - postgres
    ports:
      - 3567:3567
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE_NAME=supertokens
